import {
  FileText,
  Calculator,
  Palette,
  Code2,
  Clock,
  Wand2,
  Languages,
  ImageIcon,
  FileSearch,
  Coins,
  QrCode,
  Hash,
  Building2,
} from "lucide-react";
import { Tool } from "@/types/tool";

export const tools: Tool[] = [
  {
    id: "company-politics",
    name: "Company Politics Search",
    description: "Analyze corporate political leanings, donations, lobbying activities, and public statements.",
    icon: Building2,
    href: "/tools/company-politics",
    category: "ai",
    status: "available",
    aiPowered: true,
  },
  {
    id: "ai-writer",
    name: "AI Writer",
    description: "Generate and refine text content with AI assistance for emails, articles, and more.",
    icon: Wand2,
    href: "/tools/ai-writer",
    category: "ai",
    status: "coming-soon",
    aiPowered: true,
  },
  {
    id: "translator",
    name: "AI Translator",
    description: "Translate text between languages with context-aware AI translation.",
    icon: Languages,
    href: "/tools/translator",
    category: "ai",
    status: "coming-soon",
    aiPowered: true,
  },
  {
    id: "image-generator",
    name: "Image Generator",
    description: "Create unique images from text descriptions using AI models.",
    icon: ImageIcon,
    href: "/tools/image-generator",
    category: "creative",
    status: "coming-soon",
    aiPowered: true,
  },
  {
    id: "document-analyzer",
    name: "Document Analyzer",
    description: "Extract insights and summarize documents with AI-powered analysis.",
    icon: FileSearch,
    href: "/tools/document-analyzer",
    category: "productivity",
    status: "coming-soon",
    aiPowered: true,
  },
  {
    id: "calculator",
    name: "Smart Calculator",
    description: "Advanced calculator with unit conversions and financial functions.",
    icon: Calculator,
    href: "/tools/calculator",
    category: "utilities",
    status: "coming-soon",
  },
  {
    id: "color-picker",
    name: "Color Tools",
    description: "Pick colors, generate palettes, and convert between formats.",
    icon: Palette,
    href: "/tools/color-picker",
    category: "creative",
    status: "coming-soon",
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and transform JSON data with syntax highlighting.",
    icon: Code2,
    href: "/tools/json-formatter",
    category: "developer",
    status: "coming-soon",
  },
  {
    id: "time-zones",
    name: "Time Zones",
    description: "Convert times across time zones and schedule across regions.",
    icon: Clock,
    href: "/tools/time-zones",
    category: "utilities",
    status: "coming-soon",
  },
  {
    id: "markdown-editor",
    name: "Markdown Editor",
    description: "Write and preview Markdown with live rendering and export options.",
    icon: FileText,
    href: "/tools/markdown-editor",
    category: "productivity",
    status: "coming-soon",
  },
  {
    id: "expense-tracker",
    name: "Expense Tracker",
    description: "Track daily expenses and visualize spending patterns.",
    icon: Coins,
    href: "/tools/expense-tracker",
    category: "finance",
    status: "coming-soon",
  },
  {
    id: "qr-generator",
    name: "QR Generator",
    description: "Generate QR codes for URLs, text, and contact information.",
    icon: QrCode,
    href: "/tools/qr-generator",
    category: "utilities",
    status: "coming-soon",
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256 hashes for text and files.",
    icon: Hash,
    href: "/tools/hash-generator",
    category: "developer",
    status: "coming-soon",
  },
];

export const categories = [
  { id: "all", label: "All Tools" },
  { id: "ai", label: "AI Tools" },
  { id: "productivity", label: "Productivity" },
  { id: "utilities", label: "Utilities" },
  { id: "creative", label: "Creative" },
  { id: "developer", label: "Developer" },
  { id: "finance", label: "Finance" },
] as const;
