import {
  Building2,
  Users,
  Music,
  Search,
  TrendingUp,
  Contact2,
  ScanSearch,
  Sparkles,
  Radar,
  Moon,
  Store,
} from "lucide-react";
import { Tool } from "@/types/tool";

export const tools: Tool[] = [
  {
    id: "contact-finder",
    name: "Contact Finder",
    description: "Find publicly available contact information for individuals or organizations using AI-powered OSINT research.",
    icon: Search,
    href: "/tools/contact-finder",
    category: "ai",
    status: "available",
    aiPowered: true,
  },
  {
    id: "company-politics",
    name: "Corporate Info",
    description: "Analyze corporate political leanings, donations, lobbying activities, and public statements.",
    icon: Building2,
    href: "/tools/company-politics",
    category: "ai",
    status: "available",
    aiPowered: true,
  },
  {
    id: "business-info",
    name: "Business Info",
    description: "Deep dive into local businesses with public records, filings, ownership details, and news coverage.",
    icon: Store,
    href: "/tools/business-info",
    category: "ai",
    status: "available",
    aiPowered: true,
  },
  {
    id: "visual-rosters",
    name: "Visual Rosters",
    description: "View sports team rosters with player details and hometown mapping across NBA, NFL, NCAA, and more.",
    icon: Users,
    href: "/tools/visual-rosters",
    category: "sports",
    status: "available",
    aiPowered: true,
  },
  {
    id: "spotify",
    name: "Spotify",
    description: "Control Spotify playback, browse playlists, and search for music right from your dashboard.",
    icon: Music,
    href: "/tools/spotify",
    category: "media",
    status: "available",
  },
  {
    id: "trending",
    name: "Trending",
    description: "See what's trending on X (Twitter) and Google Trends in real-time.",
    icon: TrendingUp,
    href: "/tools/trending",
    category: "news",
    status: "available",
  },
  {
    id: "contacts",
    name: "Contacts",
    description: "View and manage your Google Contacts.",
    icon: Contact2,
    href: "/tools/contacts",
    category: "productivity",
    status: "available",
  },
  {
    id: "image-lookup",
    name: "Image Lookup",
    description: "Reverse image search using Google Lens and Bing Visual Search to find image sources and similar images.",
    icon: ScanSearch,
    href: "/tools/image-lookup",
    category: "ai",
    status: "available",
    aiPowered: true,
  },
  {
    id: "visuals",
    name: "Visuals",
    description: "AI-powered image search and generation. Find existing images or create new ones with data visualizations or imagination.",
    icon: Sparkles,
    href: "/tools/visuals",
    category: "ai",
    status: "available",
    aiPowered: true,
  },
  {
    id: "deep-search",
    name: "Deep Search",
    description: "Advanced multi-source deep web search for comprehensive research and investigation.",
    icon: Radar,
    href: "/tools/deep-search",
    category: "ai",
    status: "coming-soon",
    aiPowered: true,
  },
  {
    id: "dark-search",
    name: "Dark Search",
    description: "Explore indexed dark web content for research and security intelligence.",
    icon: Moon,
    href: "/tools/dark-search",
    category: "ai",
    status: "coming-soon",
    aiPowered: true,
  },
];

export const categories = [
  { id: "all", label: "All Tools" },
  { id: "ai", label: "AI Tools" },
  { id: "sports", label: "Sports" },
  { id: "news", label: "News" },
  { id: "media", label: "Media" },
  { id: "productivity", label: "Productivity" },
  { id: "finance", label: "Finance" },
] as const;
