import { NextResponse } from "next/server";

const XAI_API_KEY = process.env.XAI_API_KEY;
const GOOGLE_AI_API_KEY = process.env.GOOGLE_AI_API_KEY;

type ImageProvider = "grok" | "gemini";

async function generateWithGrok(prompt: string): Promise<{ imageUrl: string; revisedPrompt?: string }> {
  if (!XAI_API_KEY) {
    throw new Error("Grok API key not configured. Add XAI_API_KEY to your environment variables.");
  }

  const response = await fetch("https://api.x.ai/v1/images/generations", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${XAI_API_KEY}`,
    },
    body: JSON.stringify({
      model: "grok-2-image",
      prompt,
      n: 1,
      size: "1024x1024",
    }),
  });

  if (!response.ok) {
    let errorMessage = "Failed to generate image with Grok";
    try {
      const errorData = await response.json();
      console.error("Grok API error:", errorData);
      if (errorData.error?.message) {
        errorMessage = errorData.error.message;
      }
    } catch {
      const errorText = await response.text().catch(() => "Unknown error");
      console.error("Grok API error (text):", errorText);
    }
    throw new Error(errorMessage);
  }

  const data = await response.json();
  const imageUrl = data.data?.[0]?.url;

  if (!imageUrl) {
    throw new Error("No image generated by Grok");
  }

  return { imageUrl, revisedPrompt: data.data?.[0]?.revised_prompt };
}

async function generateWithGemini(prompt: string): Promise<{ imageUrl: string; revisedPrompt?: string }> {
  if (!GOOGLE_AI_API_KEY) {
    throw new Error("Google AI API key not configured. Add GOOGLE_AI_API_KEY to your environment variables.");
  }

  // Using Google's Imagen 3 API through the generative AI endpoint
  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-002:predict?key=${GOOGLE_AI_API_KEY}`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        instances: [{ prompt }],
        parameters: {
          sampleCount: 1,
          aspectRatio: "1:1",
          safetyFilterLevel: "block_only_high",
          personGeneration: "allow_adult",
        },
      }),
    }
  );

  if (!response.ok) {
    let errorMessage = "Failed to generate image with Gemini/Imagen";
    try {
      const errorData = await response.json();
      console.error("Gemini/Imagen API error:", errorData);
      if (errorData.error?.message) {
        errorMessage = errorData.error.message;
      }
    } catch {
      const errorText = await response.text().catch(() => "Unknown error");
      console.error("Gemini/Imagen API error (text):", errorText);
    }
    throw new Error(errorMessage);
  }

  const data = await response.json();

  // Imagen returns base64 encoded images
  const imageData = data.predictions?.[0]?.bytesBase64Encoded;

  if (!imageData) {
    throw new Error("No image generated by Gemini/Imagen");
  }

  // Return as a data URL
  const imageUrl = `data:image/png;base64,${imageData}`;

  return { imageUrl };
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { prompt, mode, action, provider = "grok" } = body;

    if (!prompt) {
      return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
    }

    // Handle image search (existing images)
    if (action === "search") {
      const searchUrls = {
        google: `https://www.google.com/search?q=${encodeURIComponent(prompt)}&tbm=isch`,
        bing: `https://www.bing.com/images/search?q=${encodeURIComponent(prompt)}`,
        unsplash: `https://unsplash.com/s/photos/${encodeURIComponent(prompt.replace(/\s+/g, "-"))}`,
        pexels: `https://www.pexels.com/search/${encodeURIComponent(prompt)}/`,
      };

      return NextResponse.json({ searchUrls, action: "search" });
    }

    // Handle image generation
    if (action === "generate") {
      // Modify prompt based on mode
      let enhancedPrompt = prompt;
      if (mode === "data") {
        enhancedPrompt = `Create a clean, professional data visualization or infographic showing: ${prompt}. Use clear labels, modern design, and make it easy to understand.`;
      } else if (mode === "imagine") {
        enhancedPrompt = `Create an imaginative, creative, and visually stunning image of: ${prompt}. Be artistic and creative with the interpretation.`;
      }

      const imageProvider = provider as ImageProvider;

      try {
        let result: { imageUrl: string; revisedPrompt?: string };

        if (imageProvider === "gemini") {
          result = await generateWithGemini(enhancedPrompt);
        } else {
          // Default to Grok
          result = await generateWithGrok(enhancedPrompt);
        }

        return NextResponse.json({
          imageUrl: result.imageUrl,
          revisedPrompt: result.revisedPrompt,
          action: "generate",
          mode,
          provider: imageProvider,
        });
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : "Failed to generate image";

        // Check for specific error types
        if (errorMessage.includes("API key not configured")) {
          return NextResponse.json(
            { error: errorMessage, isConfigError: true },
            { status: 503 }
          );
        }

        if (errorMessage.includes("billing") || errorMessage.includes("quota") || errorMessage.includes("limit")) {
          return NextResponse.json(
            { error: `${imageProvider === "gemini" ? "Google" : "xAI"} billing limit reached. Please check your account.` },
            { status: 402 }
          );
        }

        return NextResponse.json(
          { error: errorMessage },
          { status: 500 }
        );
      }
    }

    return NextResponse.json({ error: "Invalid action" }, { status: 400 });
  } catch (error) {
    console.error("Visuals API error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Failed to process request" },
      { status: 500 }
    );
  }
}

// GET endpoint to check available providers
export async function GET() {
  const providers = [];

  if (XAI_API_KEY) {
    providers.push({
      id: "grok",
      name: "Grok (Aurora)",
      description: "xAI's photorealistic image model",
      available: true,
    });
  }

  if (GOOGLE_AI_API_KEY) {
    providers.push({
      id: "gemini",
      name: "Gemini (Imagen 3)",
      description: "Google's state-of-the-art image model",
      available: true,
    });
  }

  if (providers.length === 0) {
    providers.push({
      id: "none",
      name: "No providers configured",
      description: "Add XAI_API_KEY or GOOGLE_AI_API_KEY to enable image generation",
      available: false,
    });
  }

  return NextResponse.json({ providers });
}
